language: python
python:
  - "3.4"
install:
  - pip install -r requirements.txt
  - pip install flake8 pylint coveralls
script:
  - flake8 enigma2
  - pylint enigma2
  - coverage run --source enigma2 -m unittest discover tests
after_success:
  - coveralls
